name: Autotests worker

on: push

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f ./mongo/docker-compose.yml up -d
      - name: drop containers
        run: docker-compose -f ./mongo/docker-compose.yml down

