name: Autotests worker

on: push

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create net
        run: docker network create --driver=bridge --subnet=10.10.0.0/16 test_net
      - name: Start mongo container
        run: docker-compose -f ./mongo/docker-compose.yml up -d
      - name: Start postgres container
        run: docker-compose -f ./postgres/docker-compose.yml up -d
      - name: Drop mongo container
        run: docker-compose -f ./mongo/docker-compose.yml down
      - name: Drop postgres container
        run: docker-compose -f ./postgres/docker-compose.yml down
