name: Autotests worker

on: push

jobs:
  deploy_autotest:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Ceckout autotest repository
        uses: actions/checkout@V1
      - run: ls -la


