name: autotests-worker

on: push

jobs:
  deploy_autotest:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Ceckout autotest repository
        uses: actions/checkout@v2
      - run: ls


