name: Autotests worker

on: push

jobs:
  deploy_autotest:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Ceckout autotest repository
        uses: actions/checkout@master
        with:
          name: Volkov-AWG/antology
      - uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Npm install
        run: npm install
      - name: Run autotests
        run: node server


